### ISSUE TITLE
Not auto selecting flying mount for level 60 character

### ISSUE THREAD

**Issue by DEOddle** [waldenp0nd/ravMounts#19]
I have been using RAVMounts for awhile and it has always worked fine until I decided to level a new character from 1-110 (when i started using ravmounts all my characters where at least 90).  It worked fine while all I had was ground mounts but at 60, when I learned flying mounts it will not summon any flying mounts unless I hold down the alt key while clicking the macro.  I currently have simplest config I believe possible with a macro that is simply

/ravmounts   

Thanks
Oddle

**Comment by waldenp0nd** [comment]
Hi there,

Thanks for sending in this bug report—much appreciated!

Thankfully, as seems to be a recurring theme now, Phanx has updated the code that powers the `flyable` check in Ravenous Mounts.

This is reflected in #20 and in the latest release, [1.8.8](https://github.com/waldenp0nd/ravMounts/releases/tag/1.8.8).
