### ISSUE TITLE
Right-Click Logic

### ISSUE THREAD

**Issue by OIK2** [waldenp0nd/ravMounts#7]
Could you add the ability to call a particular function (I would use it for vendor mount, but could see passenger mount also being a valid use) when the link is right-clicked upon?  In a macro this is designated with the btn:2 condition in the brackets.  I looked at the lua to see if it was a simple mod:alt/mod:shift/mod:ctrl that designated the functions, and would have added the functionality myself, but could not figure out how with the current schema.

**Comment by waldenp0nd** [comment]
Hey, thanks for the question!

I can’t believe this works... and maybe it’s just me, but this seems to do the trick?

```
/ravmounts
/stopmacro [btn:1]
/ravmounts vendor
```

**Comment by waldenp0nd** [comment]
Hey, thanks for the question!

I believe what you’re looking for is `SecureCmdOptionParse("[btn:2]")`. I'm not really interested in implementing button-checking in the AddOn at this point; although, I do appreciate the suggestion, as I learned some in the process! 😄

You can, however, implement it yourself like so:

```lua
if (specificType == "vendor" or SecureCmdOptionParse("[btn:2]")) and haveVendorMounts then
        mountSummon(RAV_vendorMounts)
end
```

or try out the [right-click-vendor branch](https://github.com/waldenp0nd/ravMounts/tree/right-click-vendor) or [related pull request](https://github.com/waldenp0nd/ravMounts/pull/8).
