### ISSUE TITLE
Favorite mounts saved on a per character basis...

### ISSUE THREAD

**Issue by ZaephirMoth** [waldenp0nd/ravMounts#9]
Greetings Mr Walden !

  I've been using your 'ravenous addon' for some time now and it works well ^^... I thank you for it ! And merely as suggestions, here are the only two (really major) additions I could imagine for it : 

  1) Would there be a way of saving favorite mounts on a per character basis ? There are multiple threads opened every year on the offical forums about that (https://us.battle.net/forums/en/wow/topic/20759646595), but I'm affraid we won't see that coming for now, so some addons already have tackled that question... And that's a shame precisely when using yours, since it relies heavily on that (default) 'favorite mounts' option. As soon as a player starts having several very different but equally important characters, the idea of tailoring them for each of them spawns fast. Mostly for RP/aesthetical purposes (matching classes, skins & equipment to selected mounts), but also sometimes for more practical needs (characters reserved for certain activities, etc.). For example, my level 30 rogue is (obviously) not having the same priorities than his older (level 101) brother or my level 70 paladin. Etc. This can be done by switching different (modified) versions of your macro, but if you had a more user-friendly idea, it would be great...

  2) Allow people to set 'class based' mounts as their favorites. Default UI doesn't allow that, which is ennoying, and the only (older) addon which tried to tackle that (with more or less success, but she could not avoid some tainting issues, from what I understood) is Phanx's (http://www.wowinterface.com/downloads/info23261-AnyFavoriteMount.html#info). Now, if you could somehow implement a solution in yours...

  Thank you again for your work anyway ! Cheers !
  Benjamin

**Comment by waldenp0nd** [comment]
Sorry to get back to you so late!

I haven’t been neglecting this; I’ve actually been considering how to implement these new features without compromising the core of the AddOn too much. Naturally, perusing Phanx’s code and comparing it to my own has left me feeling like a bit of a noob, but I’ll get something done with this ASAP.

Thanks very much for sending this in and for your kind words about my labour of love! 😄 Hope you have a fantastic New Years if I don’t manage to get this sorted by then.

**Comment by ZaephirMoth** [comment]
Don't be shy about your code ! I'm not much of a coder myself - just the basis all old players end up with, after years of tinkering with better people's work ^^ -, but it's precisely its simplicity, and yet cleverness, which makes it remarkable in the end, especially compared to the dozen of other similar addons. So you're indeed very wise in taking your time to avoid compromising your core's structure while building upon it... 
  Somehow, your addon reminds me of (author) Daft's works, which you can find partly on Curse (https://www.curseforge.com/wow/addons/sfframefade or https://www.curseforge.com/wow/addons/daftauction for example ; just type "Daft" for more) or even more on WoWInterface - that Tony fellow actually conceived interesting addons for every single part of the UI ^^, though he seems gone or taking a break now. They were purposefully very simple (no GUI, etc.) for robustness' sake, in order 'to stand the test of time' (and patches ^^) like he said...
  I just know Phanx out of reputation, from reading her threads or perussing her code lines like you said. Seems already far more complex indeed - and that's why her absence is rather sad : I haven't found any other addon than "[Class Colors](https://www.curseforge.com/wow/addons/classcolors)" which tackled the 'custom class color' question. Problem is, her's is now starting to throw errors on startup... -, but you know, her "[MountMe](https://www.curseforge.com/wow/addons/mountme)" is less complete and convenient than your 'ravenous' beast ^^... It does support druid flight forms, I think (but never tested, since I don't own a druid), but I'm not so sure about the shaman's or worgen's one - same reasons ; never tried - and in the end, your concept still offers a lot more flexibility. So you see : a coder's talent doesn't mean everything ^^... And yes, your care about this one is obvious ;) ; good work always shows anyway.

  I've actually been, these last months, more in a testing phase (about WoW) than a 'playing' one ^^ : trying to (re)think ('out of the box' ^^) about different ways of displaying each kind of information related to the game, experimenting with UIs and addons, etc. Sort of a fun mental exercise... I wouldn't say that I've tested each and every WoW addon, but hundreds of them for sure, so I'm starting to get a good grasp of what has been done and what hasn't been tried (yet), what works, how and why (or not ^^), and what (in the end) can still be reduced (with all respect due to the authors) to a bunch of 'false good ideas' - you know, like in reality, the kind of gadget with dozens of functions, but no single really useful, appropriate and functionnal one. 
  Take "[Mount Journal Enhanced](https://www.curseforge.com/wow/addons/mount-journal-enhanced)" for example : though (as I said) I'm not much of a coder, it's pretty obvious that with so much functions and different goals, it will always remain some kind of bloated gas factory, full of bugs and randomness - which it is : there are always people reporting problems in its comments -, except if one day a very talented professional coder fully commits himself to it. Too much ambitions can quickly become counter-productive...
  To be honest, I also considered using [LiteMount](https://www.curseforge.com/wow/addons/litemount), which is quite a fine work too, but though it does offer more flexibility and features than, let's say Phanx's "MountMe", it doesn't match the sheer simplicity of your addon's macro approach... and doesn't offer, for example, innate modifier keybinds for merchant mounts, group travel, etc. - that and the fact that I don't have the need for all the special 'spell based' mounts, as said above. 
  So no, as said at the beginning, don't be shy about your code and concept ^^ ! Regardless of all personal preferences, I don't know about any other mounting addon which could put it to shame ^^... The two points above really are, according to me, the only major additions which could improve it noticeably, without extending yourself out of your initial project's scope - "LiteMount" offers tons of customisation in a neat GUI, but also (for this very reason) requires a lot more work before being able to truly use it correctly - or trying to face completely different challenges - like those 'spell-based mounts'.

  Have a nice end of the year too ! Cheers !
  Benjamin

**Comment by waldenp0nd** [comment]
Hey there,

Sorry to leave this Issue lagging behind without any word from me.

I think I've decided that I want to tackle the second of your requests, robust class mount summoning, but I'd rather not add too much complexity to the AddOn with the first, that summoning lists be unique to each character.

In this case, I think I'll rely on an *inclusion setting (i.e. *`/ravmounts include class`*)* which would be checked on the fly every time a mount is requested.

**Comment by ZaephirMoth** [comment]
Hello again !

  No problem for the delay ! I'm just returning to the game myself, after a break...

  And I agree : better not add any feature that you're unsure about. And that feature obviously requires something like a 'profile-per-character' GUI or at least 'macro-per-character' one, which means a lot more work that your initial aim. You can always try to solve that issue later, if your mind is struck by a sudden bolt of genius ^^...
  Now, regarding the second point, the main question, to me, remains how to offer that option without imposing it. As long as you addon builds upon the default 'favorite mounts' system, there's no problem at all : everyone can choose to include any appreciated mount to their list. That's certainly why Phanx - who seems to have returned to WoW, since some of her addons are now getting minor updates once again - choose to (try to) improve that concept alone... Therefore, if you're just going to rely on a simple inclusing setting - which is a good idea in itself ! -, I think you'ld better make that one can be turned off by those uninterested in having those class mounts automatically show up. Especially if it means that they'll come up in priority... Another idea could be adding a new modifying key, dedicated to class mounts, but maybe this too would mean unecessary complications...

  Cheers !
  Benjamin
